### ISSUE TITLE
Where to get the MS1Mv2 train list？

### ISSUE THREAD

**Issue by wongyufei** [IrvingMeng/MagFace#13]

**Comment by IrvingMeng** [comment]
Hi, you need to generate the training list by yourself (format: "path_to_img, 0, id, 0"). 
Here is an example:
![image](https://user-images.githubusercontent.com/10399303/121641891-598fe200-cac2-11eb-88ea-5fb55a4f0b50.png)

**Comment by wongyufei** [comment]
THANKS FOR YOUR REPLY！！！
