### ISSUE TITLE
Train with mobilenet?

### ISSUE THREAD

**Issue by huytuong010101fpt** [IrvingMeng/MagFace#19]
I see the training code is using ResNetX
Can you show me how to train with mobilenet?

**Comment by IrvingMeng** [comment]
This involves a few steps:
1. add the script for mobilenet into this foler [main/models](https://github.com/IrvingMeng/MagFace/tree/main/models). 
2. add entrances for mobilenet in `load_features`: 
i.  https://github.com/IrvingMeng/MagFace/blob/main/models/magface_dist.py#L30-L49
ii. https://github.com/IrvingMeng/MagFace/blob/main/models/magface.py#L22-L41)
3. change the bash file to use your mobilenet in 
i. https://github.com/IrvingMeng/MagFace/blob/main/run/run_dist.sh#L12
ii. https://github.com/IrvingMeng/MagFace/blob/main/run/run.sh#L12

Then you are good to go.

**Comment by huytuong010101fpt** [comment]
> This involves a few steps:
> 
> 1. add the script for mobilenet into this foler [main/models](https://github.com/IrvingMeng/MagFace/tree/main/models).
> 2. add entrances for mobilenet in `load_features`:
>    i.  https://github.com/IrvingMeng/MagFace/blob/main/models/magface_dist.py#L30-L49
>    ii. https://github.com/IrvingMeng/MagFace/blob/main/models/magface.py#L22-L41)
> 3. change the bash file to use your mobilenet in
>    i. https://github.com/IrvingMeng/MagFace/blob/main/run/run_dist.sh#L12
>    ii. https://github.com/IrvingMeng/MagFace/blob/main/run/run.sh#L12
> 
> Then you are good to go.

wow thank u so much, let me try

**Comment by sfxeazilove** [comment]
Hi, did you get this done and how did you do it?
