### ISSUE TITLE
I wonder if you have any weight files of your model.

### ISSUE THREAD

**Issue by suesuekkim** [IrvingMeng/MagFace#21]
I'm trying to do the face recognition with your MagFace model and wonder if you have any of the pretrained weight file of MagFace model, since I can save the time for training. 
I'm not in the conditions for training the model in my computer, and trying to implement the evaluation part. 
I really appreciate if you can share your weight files.

![image](https://user-images.githubusercontent.com/78398919/128730048-3b0a6255-2f86-4ae6-8ef2-14cccf819fd8.png)

Thank you.

**Comment by IrvingMeng** [comment]
Hi,

You can find several trained model in the model zoo section in ReadMe. The first model is recommended to use.

![image](https://user-images.githubusercontent.com/10399303/128803862-be2211ec-0413-467b-8904-11297e9d7eb7.png)
