### ISSUE TITLE
How to reproduce the cluster evaluation results of the IJBB dataset in the paper?

### ISSUE THREAD

**Issue by hustllz** [IrvingMeng/MagFace#22]
Thank you for your great research and the open source code. 
We want to evaluate the improvement for the cluster task but the code in "eval/eval_cluster" is empty. Do you have the plan to public the code of this part? Do you have any suggestions for cluster testing on IJBB? 
Thank you!

**Comment by IrvingMeng** [comment]
Hi,

We are sorry for the delay and will release related codes when they are ready. Recently, we have very limited time to organize them. 

You can start with the `scikit-learn` package for the clustering task. Here are some examples.
```python3
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering        
from sklearn.cluster import DBSCAN       
from sklearn.cluster import SpectralClustering
from sklearn.cluster import AffinityPropagation
from sklearn.metrics import normalized_mutual_info_score, precision_score, recall_score
```

This [repo](https://github.com/Zhongdao/gcn_clustering/blob/master/utils/utils.py#L52) provides codes for B-cubed precision, recall, and F1. You also train GCN models with the repo.

**Comment by hustllz** [comment]
Thanks for your reply!
I notice the sentence "We adopt the IJB-B dataset as the benchmark as it contains a clustering protocal ......". Could you please tell me how to access the "clustering protocal"? I guess it's in the original IJB dataset? I have acquired the license to download the whole IJB dataset. But the total size is 300+GB and the download speed is desperate...

**Comment by IrvingMeng** [comment]
Yes, the clustering protocols are from the source IJB-B dataset.  Here is the directory structure. 
![1](https://user-images.githubusercontent.com/10399303/130002085-6fda2579-cbd1-430e-a353-e2082ffa5b5e.png)

We are sorry to hear the downloading speed is low. We cannot share our copy of the dataset as the license states "No further distribution of the data without express written permission from NIST". 

BTW, you can contact me at Wechat (IrvingMeng) for quick responses.
