### ISSUE TITLE
quality assessment through the error-versus-reject curves

### ISSUE THREAD

**Issue by WWWJL** [IrvingMeng/MagFace#24]
hi, about evaluate the quality assessment on LFW/CFPFP/AgeDB via the error-versus-reject curves,Can you provide the corresponding code?thanks!

**Comment by IrvingMeng** [comment]
Hi,

Code for plotting the curves is now available in the repo.

Best,
Qiang

**Comment by WWWJL** [comment]
ok,thanks！:)



---Original---
From: "Qiang ***@***.***&gt;
Date: Thu, Sep 9, 2021 12:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IrvingMeng/MagFace] quality assessment through the error-versus-reject curves (#24)




 
Hi,
 
Code for plotting the curves is now available in the repo.
 
Best,
 Qiang
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WWWJL** [comment]
by the way, please provide the model used in the quality assessment ,thanks



---Original---
From: "Qiang ***@***.***&gt;
Date: Thu, Sep 9, 2021 12:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IrvingMeng/MagFace] quality assessment through the error-versus-reject curves (#24)




 
Hi,
 
Code for plotting the curves is now available in the repo.
 
Best,
 Qiang
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IrvingMeng** [comment]
Using current released model should be enough to get similar results. 

For interests of our company, we can only release that model for research purpose (e.g., using that model as a baseline in your own paper). Please send us an official email with detailed explanations if you want it.

**Comment by WWWJL** [comment]
***@***.***



---Original---
From: "Qiang ***@***.***&gt;
Date: Thu, Sep 9, 2021 13:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IrvingMeng/MagFace] quality assessment through the error-versus-reject curves (#24)




 
Using current released model should be enough to get similar results.
 
For interests of our company, we can only release that model for research purpose (e.g., using that model as a baseline in your own paper). Please send us an official email with detailed explanations if you want it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WWWJL** [comment]
21725028atzju.edu.cn



---Original---
From: "Qiang ***@***.***&gt;
Date: Thu, Sep 9, 2021 13:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IrvingMeng/MagFace] quality assessment through the error-versus-reject curves (#24)




 
Using current released model should be enough to get similar results.
 
For interests of our company, we can only release that model for research purpose (e.g., using that model as a baseline in your own paper). Please send us an official email with detailed explanations if you want it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WWWJL** [comment]
ok,thanks



---Original---
From: "Qiang ***@***.***&gt;
Date: Thu, Sep 9, 2021 13:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IrvingMeng/MagFace] quality assessment through the error-versus-reject curves (#24)




 
Using current released model should be enough to get similar results.
 
For interests of our company, we can only release that model for research purpose (e.g., using that model as a baseline in your own paper). Please send us an official email with detailed explanations if you want it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
