### ISSUE TITLE
face_align.pyt

### ISSUE THREAD

**Issue by fisakhan** [IrvingMeng/MagFace#26]
The following link under section "Basic Training" is no more available. 
https://github.com/deepinsight/insightface/blob/master/recognition/common/face_align.py

The dropbox link for downloading MS1MV2 is also not working. 
Can you please fix these issues?

**Comment by IrvingMeng** [comment]
Hi, 

The link for script `face_align.py` is now here: https://github.com/deepinsight/insightface/blob/cdc3d4ed5de14712378f3d5a14249661e54a03ec/python-package/insightface/utils/face_align.py. 

The dropbox link is from MS1M-ArcFace in https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_.  You can open an issue in their repo and let them fix the dropbox link.

Best, 
Qiang

**Comment by fisakhan** [comment]
Thanks @IrvingMeng 
MS1M-ArcFace is now faces_emore.zip (12G) on Google Drive
 https://drive.google.com/file/d/1SXS4-Am3bsKSK615qbYdbA_FMVh3sAvR/view
