### ISSUE TITLE
What model did you used in the paper?

### ISSUE THREAD

**Issue by fisakhan** [IrvingMeng/MagFace#27]
What model did you use to get histograms of Fig 5 in the paper? I used magface_epoch_00025.pth on LWF and got this histogram, where the magnitude values are lesser than what Fig 5 reports.
![magface_LFW](https://user-images.githubusercontent.com/48552619/135406764-576b4087-2320-49b1-b1d7-c1e08450a958.png)

**Comment by IrvingMeng** [comment]
Hi, 

Fig 5 is based on a very early model whose parameters are set empirically.  The range of the magnitudes can differ (e.g., the magnitudes increases if we use large lambda_g) when parameters change.

The released model is well tuned for recognition performances. The magnitudes are smaller but the overall trends on datasets should be the same. 

Best,
Qiang

**Comment by fisakhan** [comment]
it means, I'm not doing it wrong at inference. Thanks @IrvingMeng
