### ISSUE TITLE
Code for face quality assessment

### ISSUE THREAD

**Issue by bigAndSmall** [IrvingMeng/MagFace#3]
Hi， I'm looking for your code about quality assessment. Hope you can put it online soon, Thanks a lot!

**Comment by IrvingMeng** [comment]
Hi there. We predict face qualities by calculating feature magnitudes (e.g.,  np.linalg.norm(feats)). You can find detailed steps in the toy example [link](https://github.com/IrvingMeng/MagFace/blob/main/inference/examples.ipynb).
