### ISSUE TITLE
Partially parameters loading after training

### ISSUE THREAD

**Issue by rzamarefat** [IrvingMeng/MagFace#36]
Thank you for this awesome repo. I have trained MagFace on my own dataset and everything was completely ok. But the problem is that when I want to use this trained model there happens to be the following error:
=> Not all weights loaded, model params: 925, loaded params: 475
I cannot trace the problem. Can you please give me a hint what I have done wrong in the training?

**Comment by IrvingMeng** [comment]
Hi,

Thanks for trying MagFace. The error is raised by https://github.com/IrvingMeng/MagFace/blob/b1ae3abdfa250348188807375734d8fdacd9770e/inference/network_inf.py#L86-L87

This part checks whether the structure of the built model is consistent with that to be loaded. You have to define the corresponding network structure by the param "--arch" if the backbone is not "iresnet100".

https://github.com/IrvingMeng/MagFace/blob/b1ae3abdfa250348188807375734d8fdacd9770e/inference/gen_feat.py#L28-L29

**Comment by rzamarefat** [comment]
Thank You. It solved my problem
