### ISSUE TITLE
Low ACC for KDEF dataset

### ISSUE THREAD

**Issue by rzamarefat** [IrvingMeng/MagFace#37]
Hi, thank you for this awesome repo. I have tried to generate embs on KDEF dataset. This dataset contains samples such as:
![AF01AFFL](https://user-images.githubusercontent.com/79300456/147851617-0b3f1a85-2f23-4443-98aa-87820dbdfcdc.JPG)
![AF01AFHL](https://user-images.githubusercontent.com/79300456/147851620-7a5643b8-e709-4b08-8a56-d18405301c23.JPG)
![AF01AFS](https://user-images.githubusercontent.com/79300456/147851624-4fda0878-cbce-48cb-be90-ac966264f4ac.JPG)
I have used SVM for classifying the generated embs but got a very low acc of 50%. Please note that I have removed images of faces which are depicting the profile. Based on my explanation, what can be the problem? Should I remove the images which are partially straight also (images like the second image)?

**Comment by IrvingMeng** [comment]
Hi, 

Could you provide details of feature generation? For example, how do you align the faces and what scripts used?

**Comment by rzamarefat** [comment]
Thank you for your response. Firstly based on the following images, which are the cropped versions of the images shown above, our dataset does not need any alignment (correct me if I'm making a mistake)
![AF01ANS](https://user-images.githubusercontent.com/79300456/148369653-6d61b091-7a9f-43aa-9acb-acce1f6a08d8.JPG)
![AF01DIS](https://user-images.githubusercontent.com/79300456/148369673-7f1556aa-9211-41f7-a323-c8696ae7dce8.JPG)
As you can see these images are cropped in a way that the images are focused on the face of the person. However, I don't do any alignment because I reckon that they are aligned.
In terms of feature generation I am using the module provided here ( "MagFace/inference/gen_feat.py" ). Actually I have used the very same way for other datasets and the generated features were, thanks to your brilliant work, of great quality. For example, when I used SVM for classifying IDs of people within a dataset, the achieved score were above 99.0. But for this dataset (so-called KDEF) the biggest score for SVM that I get is approximately around 45 to 50%. This caused me a insolvable problem. Thank you in advance for your help

**Comment by IrvingMeng** [comment]
I notice that your cropped images are different from the corrected ones, especially for profile faces. For example, noses tend to be placed in the centers of example images[1] while your third image is at the contrary of that.
As the alignment step highly affects recognition performances, I suggest you re-align the faces to see if that's the cause.

[1] https://github.com/IrvingMeng/MagFace/tree/main/inference/toy_imgs

**Comment by rzamarefat** [comment]
I have done as you said and now my images such as the following:
![AF01ANFL](https://user-images.githubusercontent.com/79300456/148389689-8458cd19-ec22-4fd5-baeb-81dc4da28e4a.JPG)
![AF01NEHL](https://user-images.githubusercontent.com/79300456/148389720-78d38dff-fad2-484a-a6fd-d13c343370b1.JPG)
Please note that I am using MTCNN for alignment. The ACC of SVM is increased to 70% but still it is very low.

**Comment by IrvingMeng** [comment]
I see. Do you normalize all the features before using SVM. Otherwise, the low performance may caused by the domain invariance. You may need to re-train the model if that's the case.

**Comment by rzamarefat** [comment]
Actually I haven't normalize them. And this may cause the problem of low acc (I will try that and see if it solves it). Besides, I have two questions. Can we actually train MagFace on any other dataset containing images of sth else other than face of human beings? As the developer of this brilliant paper can you see it possible that after training we could get any good quality representation of some other objects?

**Comment by IrvingMeng** [comment]
1. domain invariance means the distributions of training and testing dataset are different. 
2. I cannot guarantee good results for datasets besides faces. However, I believe it can still work in theory as long as the data distributions are suitable.
