### ISSUE TITLE
Eval Data 

### ISSUE THREAD

**Issue by WesRobbins** [IrvingMeng/MagFace#38]
I am unable to access the data on baidu. Can lfw/cfp/agedb eval data be made available on google drive?

**Comment by IrvingMeng** [comment]
Hi, I just uploaded the data to gdrive. Here is the link: https://drive.google.com/file/d/1HBGwyTFnl4Bt4hl5BpLE3t__J84R72TX/view

**Comment by WesRobbins** [comment]
Thank you!
