### ISSUE TITLE
None parameters loading after training

### ISSUE THREAD

**Issue by DoLNw** [IrvingMeng/MagFace#40]
Hello, I'm new to PyTorch.

I have a problem on training.

First, I write the "ms1m_train.list" for few datasets and train the model by run "./run.sh"
below is the ms1m_train.list:
![Screen Shot 2022-02-24 at 10 30 41 PM](https://user-images.githubusercontent.com/35894540/155543741-fce11d69-c3d5-4f51-9663-05481a5d838f.png)

then I run command "./eval.sh /Volumes/jc_sandisk/MS1Mv2_dataset/mymagfacemodel/test/00010.pth official 100" for eval, but I got the error "=> Not all weights loaded, model params: 925, loaded params: 0".

Maybe it's a simple problem, but it stuck me.

By the way, "MODEL_ARC" in "run.sh" is "iresnet100".

**Comment by DoLNw** [comment]
I just want to go through all the process first and use get dataset, the char on bottom right in the picture "Z" is mistyped.

**Comment by IrvingMeng** [comment]
Hi, could you share the model `/Volumes/jc_sandisk/MS1Mv2_dataset/mymagfacemodel/test/00010.pth`  so I can help debugging?

**Comment by DoLNw** [comment]
That's great! can you give my your e-mail and I can send it to you. thank u!

**Comment by IrvingMeng** [comment]
irvingmeng@outlook.com

**Comment by IrvingMeng** [comment]
Your issue should be solved by adding the following code after https://github.com/IrvingMeng/MagFace/blob/main/inference/network_inf.py#L73-L82:

```
        # assert k == 'features.'
        if k in model.state_dict().keys() and \
           v.size() == model.state_dict()[k].size():
            _state_dict[k] = v
```
I guess your model is trained by some external scripts (without DataParallel or DistributedDataParallel). The names of model weights are different as follows:

![image](https://user-images.githubusercontent.com/10399303/155722100-5b751868-4844-4d53-a777-276730b8fd75.png)

**Comment by DoLNw** [comment]
thank you for your help, i just mis comment the code "model = torch.nn.DataParallel(model).cuda()" in "trainer.py".
Now I uncomment it and I get the right model, thank you once again.
