### ISSUE TITLE
无法下载renset18对应的log链接

### ISSUE THREAD

**Issue by JayL323** [IrvingMeng/MagFace#41]
作者您好，Model Zoo中resnet18对应的log链接中，给出的是resnet50的log，能麻烦您重新提交一下吗？
模型：MagFace | iResNet18
![image](https://user-images.githubusercontent.com/24243059/156339740-c65c84b8-09e7-4258-a360-656425912de9.png)

百度网盘对应的链接：
![image](https://user-images.githubusercontent.com/24243059/156338862-bb158314-63d8-48f0-9f81-7efb27b2f2f4.png)

**Comment by IrvingMeng** [comment]
多谢提醒，已更新哈。

**Comment by JayL323** [comment]
感谢作者！！！
