### ISSUE TITLE
关于 FNMR 的计算方法

### ISSUE THREAD

**Issue by Actstone** [IrvingMeng/MagFace#44]
https://github.com/IrvingMeng/MagFace/blob/dbd0c5b587d62b3ee51933e41b68f70e0e6db8bf/eval/eval_quality/eval_quality.py#L134

嘿，为什么这样计算 fnmr ？
我查阅其他的资料，我的理解应该是 `fnmr = 1.0 * num_acc / num_query` 。
 能不能解释一下，谢谢！

**Comment by IrvingMeng** [comment]
参考https://zhuanlan.zhihu.com/p/50943686

**Comment by Actstone** [comment]
好的，我学习一下。谢谢
