### ISSUE TITLE
pair_list 是如何得到的？

### ISSUE THREAD

**Issue by Actstone** [IrvingMeng/MagFace#45]
https://github.com/IrvingMeng/MagFace/blob/dbd0c5b587d62b3ee51933e41b68f70e0e6db8bf/eval/eval_quality/eval_quality.py#L19

嘿，对于数据集 LFW，代码里这个 pair_list 是怎么得到的？
是直接用 LFW 提供的[pairs.txt](http://vis-www.cs.umass.edu/lfw/pairs.txt) 吗？
但是，我使用[pairs.txt](http://vis-www.cs.umass.edu/lfw/pairs.txt) 并没有复现成功 paper 画的 EVRC。

**Comment by Actstone** [comment]
我找到了。谢谢

**Comment by IrvingMeng** [comment]
pair.txt在识别的评测里。evaluation-Face Recognition 里面第一步可以下载。

**Comment by Actstone** [comment]
好的，谢谢

**Comment by csn223355** [comment]
作者您好，我想用你们的模型来测试一批人脸图片的人脸质量，但是我不知道如何生成pair.list，这个pair.list在人脸识别和评估的过程中起什么样的作用呢？
