### ISSUE TITLE
Why is ImgInfLoader  not performing any pre-processing? (a bit URGENT)

### ISSUE THREAD

**Issue by arunsubk** [IrvingMeng/MagFace#49]
Hi All,
A bit urgent. Hence would really be thankful if someone with a quick answer to take the time to reply to me.

A look at the following class https://github.com/IrvingMeng/MagFace/blob/dbd0c5b587d62b3ee51933e41b68f70e0e6db8bf/inference/gen_feat.py#L52 shows that there is no pre-processing done, apart from just loading the image using cv2. In contrast, Insightface (which also uses the same meta files) performs face alignment https://github.com/deepinsight/insightface/blob/d4d4531a702e22cc7666cda2de6db53f4dc2e4db/recognition/_evaluation_/ijb/ijb_evals.py#L238 . While using the same meta, I am wondering why there is a difference. Am I to understand that magface does not use any pre-processing? (is there no crop+align using landmark here?)

Thanks,

**Comment by IrvingMeng** [comment]
Hi. MagFace requires the same pre-processing as Insightface. `gen_feat.py` assumes that images are already cropped and aligned offline.
If images are not processed in advance, you need to preprocess them in the dataloader.

**Comment by arunsubk** [comment]
Thanks a lot for the instant response Irving. Thanks for the great work and the repo. (just on another note, might really help if  if addition to baidu, a gdrive of IJB tar is provided. Baidu registration is getting difficult for me because it requires a phone number. I had to find an alternate location in Insightface to get the IJB tar file). Please ignore my comment if it is not relevant or feasible for reasons you know best.

**Comment by IrvingMeng** [comment]
IJB tar files are not provided in gdrive due to my limited access to google services. I will attempt to upload them to gdrive recently and let you know if I succeed. 
Please expect late responses as the connections are truly restricted and unstable.

**Comment by IrvingMeng** [comment]
Hi arunsubk,
IJB files are availabel in google drive now. You can find the links in Readme.

**Comment by arunsubk** [comment]
Hi IrvingMeng,

Thanks a lot for this and also to all your responses on the thread. Really helped me move ahead with reproducing magface on IJB. 

Warm regards,
Arun
