### ISSUE TITLE
Cannot get the same performance as paper

### ISSUE THREAD

**Issue by bigAndSmall** [IrvingMeng/MagFace#5]
Hi，I've tried your pre-training model in ijbc, but i cannot get the same result as your paper. Maybe beacause of the testing standard? Hope you can reply to me soon.

**Comment by bigAndSmall** [comment]
![image](https://user-images.githubusercontent.com/63275564/114375486-43939d00-9bb7-11eb-9612-5624514e0989.png)

**Comment by IrvingMeng** [comment]
The result seems too wired and I guess it's caused by wrongly extracted features. Could you double check that step?
Feel free to contact me at WeChat (IrvingMeng) or FaceBook (ustcmq) if you need more help.
