### ISSUE TITLE
Is the lfw dataset link provided in this repo aligned to five facial landmarks too?

### ISSUE THREAD

**Issue by arunsubk** [IrvingMeng/MagFace#58]
Dear Repo Head @IrvingMeng ,

Thanks a lot for the great work and share. I see one of the requirements during training is to crop images to 112x112 and then align the face to 5 facial landmarks. However, I see no such pre-processing (only 0 mean, 1 std normalization) on test dataset (for example lfw). Does this mean the lfw data link you referred to has already been aligned? But a basic investigation of the images do seem to indicate the images have been aligned. But please correct me if I am wrong.

Thanks,
Arun

**Comment by IrvingMeng** [comment]
You are right. The provided images are aligned in advance.
