### ISSUE TITLE
why the FMR is divided directly by 10

### ISSUE THREAD

**Issue by JH-Lam** [IrvingMeng/MagFace#61]
hi , when I dived into the eval_quality.py#perform_1v1_quality_eval(), I found that this metric is based on division on 10. but I think(before) it should be a real "False Match Rate(ie. FAR) = #number of matched pairs / #total paris b/w different faces". so I think it should  not be devided by 10. pseudo code block what you did:

`
fmr = 1

loop:
    ....do something
    ....fmr  /= 10

`

please detail more , thanks

**Comment by JH-Lam** [comment]
@IrvingMeng hi there, pls give some clues

**Comment by IrvingMeng** [comment]
Hi, the goal is to find the FNMR@FMR=0.001 (at different ratios of ignored low-quality faces). This pursuit involves a specific process: with each iteration, we divide the 'idx' by 10 and find the correspoding threshold(https://github.com/IrvingMeng/MagFace/blob/main/eval/eval_quality/eval_quality.py#L132) , subsequently resulting in  a FMR that is 1/10 of the FMR from the prior loop.
When FMR = 0.001, we skip the loop and record that FNMR.

**Comment by JH-Lam** [comment]
I illustrate your code block logics below:
![Snipaste_2023-08-30_13-56-50](https://github.com/IrvingMeng/MagFace/assets/53388447/66b7e49c-4168-45d2-b709-f8021092f258)
1. is the workflow right?
2. do you mean the FMR you did is an **estimated** value but not a real calculation derived like this https://blog.csdn.net/Will_Ye/article/details/107167344 ? in other words ,  assume the leading part of neg_dists are 'false match' ? and why

**Comment by IrvingMeng** [comment]
The FMR is not estimated. The first "idx" values are false match as their values are larger than current threshold (https://github.com/IrvingMeng/MagFace/blob/main/eval/eval_quality/eval_quality.py#L132C13-L132C36) .
