### ISSUE TITLE
Pretrained models on google drive

### ISSUE THREAD

**Issue by seba-eng** [IrvingMeng/MagFace#65]
Hi, is it possible to get the pretrained models of the Resnet50 and Resnet18 on google drive (or anything similar)? It is difficult to impossible to access Baidu Drive outside China. Thanks for the help

**Comment by IrvingMeng** [comment]
Hi. I have uploaded two models to google drive. You can find the links in the updated ReadMe.

**Comment by seba-eng** [comment]
thank you! That was super helpful.

**Comment by SebastianEngelhardt** [comment]
Hey, I know this is an old issue, but could you also upload the training logs to google drive?
