### ISSUE TITLE
Difference in the evaluation cases

### ISSUE THREAD

**Issue by vkouam** [IrvingMeng/MagFace#67]
Hello, 
what is please the difference between eval_cluster, eval_quality and eval_recognition. When am I supposed to use which of them?

Thanks in advance :)

**Comment by IrvingMeng** [comment]
Hi, these parts correspond to tasks of face clustering, face quality assessment and face recognition. You can find some details in the paper.

**Comment by vkouam** [comment]
Allright! Thank you @IrvingMeng
