### ISSUE TITLE
Poster/Slide introduction typo

### ISSUE THREAD

**Issue by torss** [IrvingMeng/MagFace#9]
Hi, interesting work!
I think there is a little typo in the "Introduction" part of the poster:
~~It says "pushs the easier samples away", but should presumably say "pushes the harder samples away".~~
Edit: This also applies to the "Introduction — Goals" slide.
Edit 2: Never mind, I just misread the sentence. :)
There still is a typo with "pushs" -> "pushes", but that's unimportant.

**Comment by IrvingMeng** [comment]
Will fix the typo. Thanks! :)
